### ISSUE TITLE
error when run the file" \examples\geometry_engine\airfoil\airfoil_xfoil_parallel.py"

### ISSUE THREAD

**Issue by gkbatchelor** [peterdsharpe/AeroSandbox#37]
when run the  airfoil_xfoil_parallel.py file under spyder envirement, the out put are as follows:
 
 Running XFoil sweeps on Airfoil sd7032...
Traceback (most recent call last):

  File "D:\PROGRAM\python\AeroSandbox\examples\geometry_engine\airfoil\airfoil_xfoil_parallel.py", line 8, in <module>
    parallel=True

  File "C:\ProgramData\Anaconda3\lib\site-packages\aerosandbox\geometry\airfoil.py", line 987, in get_xfoil_data
    pool = mp.Pool(mp.cpu_count())

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\context.py", line 119, in Pool
    context=self.get_context())

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\pool.py", line 176, in __init__
    self._repopulate_pool()

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\pool.py", line 241, in _repopulate_pool
    w.start()

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\multiprocess\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)

AttributeError: module '__main__' has no attribute '__spec__'

**Comment by puiseux** [comment]
Error for me too, on macos, i tried to run `/AeroSandbox/examples/geometry_engine/airfoil/airfoil_xfoil_parallel.py` as is
```
Running XFoil sweeps on Airfoil sd7032...
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
Exception ignored in: <function XFoil.__del__ at 0x7f832eb72f28>
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 66, in __del__
    handle = self._lib._handle
AttributeError: 'XFoil' object has no attribute '_lib'
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/puiseux/GitHub/AeroSandbox/aerosandbox/geometry/airfoil.py", line 968, in get_xfoil_data_at_Re
    reset_bls=True,
  File "/Users/puiseux/GitHub/AeroSandbox/aerosandbox/geometry/airfoil.py", line 805, in xfoil_aseq
    xf = XFoil()
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/xfoil/xfoil.py", line 56, in __init__
    self._lib = cdll.LoadLibrary(self._lib_path)
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/var/folders/n4/bcbxk0g53j1f88t5q3ghv2_c0000gn/T/tmp7is24tqu.dylib, 6): Library not loaded: /usr/local/lib/libgfortran.3.dylib
  Referenced from: /private/var/folders/n4/bcbxk0g53j1f88t5q3ghv2_c0000gn/T/tmp7is24tqu.dylib
  Reason: image not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/puiseux/GitHub/AeroSandbox/examples/geometry_engine/airfoil/airfoil_xfoil_parallel.py", line 8, in <module>
    parallel=True
  File "/Users/puiseux/GitHub/AeroSandbox/aerosandbox/geometry/airfoil.py", line 998, in get_xfoil_data
    runs_data = pool.map(get_xfoil_data_at_Re, Res)
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/multiprocess/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/puiseux/anaconda2/envs/Apero/lib/python3.7/site-packages/multiprocess/pool.py", line 657, in get
    raise self._value
OSError: dlopen(/var/folders/n4/bcbxk0g53j1f88t5q3ghv2_c0000gn/T/tmp7is24tqu.dylib, 6): Library not loaded: /usr/local/lib/libgfortran.3.dylib
  Referenced from: /private/var/folders/n4/bcbxk0g53j1f88t5q3ghv2_c0000gn/T/tmp7is24tqu.dylib
  Reason: image not found

```

**Comment by antoniosgeme** [comment]
I was also getting an error running this example. For me the issue seems to be with stdout_redirected which an attempt to silence xfoil output in aerosandbox/tools/string_formatting.py. By silencing its call in method xfoil_aseq of airfoil.py I fixed the issue

**Comment by peterdsharpe** [comment]
Hi all,

Thank you all for the bug reports, and sorry for the delayed response!

These are three separate bugs for each commenter, two of which are due to underlying libraries:
* @gkbatchelor is seeing an issue deep inside the `multiprocess` library ([homepage here](https://pypi.org/project/multiprocess/)); unfortunately I'm not well-versed enough in the inner workings of this library to be of much help debugging this. A quick fix is to flag `parallel=False`, which will run the code in serial mode, bypassing the `multiprocess` module entirely.

* @puiseux is seeing an issue within the underlying `xfoil-python` library ([GitHub source here](https://github.com/DARcorporation/xfoil-python)). Unfortunately, this library seems to be no longer maintained and not compatible with Python 3.8+ on Windows or any Python version on Mac/Linux - which is a shame because direct XFoil calls from Python were really useful. Dropped issue ticket to follow here: https://github.com/DARcorporation/xfoil-python/issues/9

* @antoniosgeme is seeing an issue with `stdout_redirected()` which is inside `aerosandbox`. We're currently tracing this issue; it seems to throw errors somewhat randomly on various users' computers, but we're not yet sure what's causing that. AeroSandbox v3.0.0 is about to release soon, which, along with adding *tons* and *tons* of features, documentation, and tutorials, will remove this function until we can do more testing and debugging here.

**Comment by antoniosgeme** [comment]
@peterdsharpe  I am looking forward to 3.0.0. After upgrading to python 3.8.5, I am no longer able to reproduce the error since xfoil-python won't build in the first place. Seems like there is a PR to fix that but as you said the repo is likely not maintained. 

Previous version: 3.7.9
ASB version : 2.2.10
Windows 10

sys.stdout.fileno() was working from command line but not from IPython or IDLE.
