### ISSUE TITLE
VLM for trajectory optimization

### ISSUE THREAD

**Issue by cdhainaut** [peterdsharpe/AeroSandbox#81]
Hi,

I am trying to use vortex lattice methods for optimal control problems. I successfully used the AeroBuildup module for optimizing a trajectory, but optimizing the design with this module doesn't make sense because my design isn't to adapted to it.
When trying to switch to vortex lattice method with a number of variables > 1 using the following code:

```python
import aerosandbox.numpy as np
import aerosandbox as asb

opti = asb.Opti()

n_vars = 2
alpha = opti.variable(n_vars=n_vars)
beta = np.linspace(0,2,n_vars)

vlm_results = asb.VortexLatticeMethod(
    airplane=airplane,
    op_point=asb.OperatingPoint(
        atmosphere=asb.Atmosphere(),
        alpha = alpha,
        beta = beta
    )
).run()

opti.subject_to([
    vlm_results["F_g"][1] = 100
])

sol = opti.solve()
```

I get this error:

```
Traceback (most recent call last):
  File "AeroSandbox/aerosandbox/aerodynamics/aero_3D/vortex_lattice_method.py", line 197, in run
    steady_freestream_velocity = self.op_point.compute_freestream_velocity_geometry_axes()  # Direction the wind is GOING TO, in geometry axes coordinates
  File "AeroSandbox/aerosandbox/performance/operating_point.py", line 235, in compute_freestream_velocity_geometry_axes
    return self.compute_freestream_direction_geometry_axes() * self.velocity
  File "AeroSandbox/aerosandbox/performance/operating_point.py", line 231, in compute_freestream_direction_geometry_axes
    return self.compute_rotation_matrix_wind_to_geometry() @ np.array([-1, 0, 0])
  File "AeroSandbox/aerosandbox/performance/operating_point.py", line 212, in compute_rotation_matrix_wind_to_geometry
    alpha_rotation = np.rotation_matrix_3D(
  File "AeroSandbox/aerosandbox/numpy/rotations.py", line 104, in rotation_matrix_3D
    return array(rot)
  File "/AeroSandbox/aerosandbox/numpy/array.py", line 31, in array
    return _cas.vertcat(
  File "/home/charles/miniconda3/envs/py39/lib/python3.9/site-packages/casadi/casadi.py", line 466, in vertcat
    def vertcat(*args): return _vertcat(args)
  File "/home/charles/miniconda3/envs/py39/lib/python3.9/site-packages/casadi/casadi.py", line 20204, in _vertcat
    return _casadi._vertcat(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function '_vertcat'.
  Possible prototypes are:
    _vertcat([Sparsity])
    _vertcat([DM])
    _vertcat([SX])
    _vertcat([MX])
  You have: '(([MX|int],DM,[MX|int]))'
```

I guess this `compute_rotation_matrix_wind_to_geometry` does not support mixed types. Is it a feature that is planned to be available any time soon ?

Thank you

**Comment by carlitador** [comment]
Hi Peter,
Thank you for answering. For your second point, are you really sure its only a matter of 10 code lines ? Looking at the code, freestream_velocity consists in a Nx3 matrix, where N is the number of collocation points. 
```python
freestream_velocities = np.add(
    wide(steady_freestream_velocity) , rotation_freestream_velocities
)
# Nx3, represents the freestream velocity at each panel collocation point (c)
```
As CasADi MX not support n > 2 dimensions, how would you shape the matrix so that it accounts for this third "time" dimension ?

The only workaround I see to solve this issue is to consider constant spanwise freestream velocity, which can be limiting in some cases. 
What do you think ?

Thank you

**Comment by carlitador** [comment]
Thanks, I will definitely have a look at it.
```python
    constant = gamma / (4 * np.pi)

    u = np.multiply(
        constant,
        (
                a_cross_b_x * term1 +
                a_cross_u_x * term2 -
                b_cross_u_x * term3
        )
    )
    v = np.multiply(
        constant,
        (
                a_cross_b_y * term1 +
                a_cross_u_y * term2 -
                b_cross_u_y * term3
        )
    )
    w = np.multiply(
        constant,
        (
                a_cross_b_z * term1 +
                a_cross_u_z * term2 -
                b_cross_u_z * term3
        )
    )
```
If gamma is not a vector but a matrix of shape n x m with n being the number of steps and m being the number of panels. In this case, don't you think the loop on the number of panels could be too expansive ?

Thanks again
